---
apiVersion: v2
description: A Helm chart to create TrustyAI service ⛵️
name: trustyai
version: 0.0.1
home: https://rhoai-mlops.github.io/mlops/
maintainers:
  - name: RHRolun
  - name: rcarrata
  - name: ckavili