project: music
provider: local
registry:
    registry_type: sql
    path: postgresql://feast:feast@feast:5432/feast
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
        echo: false
        pool_pre_ping: true
online_store:
    type: postgres
    host: feast
    port: 5432
    database: feast
    db_schema: feast
    user: feast
    password: feast
offline_store:
    type: file
entity_key_serialization_version: 2