---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-folder
  namespace: {{ .Release.Namespace }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  resyncPeriod: 5m
  title: {{ .Release.Name }} {{ .Release.Namespace }} Dashboards