---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: {{ .Values.name }}
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    {{- if .Values.autoscaling }}
    autoscaling.knative.dev/target: "1"
    {{- end }}
  name: {{ .Values.name }}
  finalizers:
    - inferenceservice.finalizers
  labels:
    # networking.knative.dev/visibility: cluster-local
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    {{- if .Values.canary }}
    canaryTrafficPercent: {{ .Values.canary.trafficPercent }}
    {{- end }}
    containers:
      - args:
          - '--model_name={{ .Values.name }}'
          - '--port=8001'
          - '--rest_port=8085'
          - '--model_path=/mnt/models'
          - '--file_system_poll_wait_seconds=0'
          - '--grpc_bind_address=0.0.0.0'
          - '--rest_bind_address=0.0.0.0'
          - '--target_device=AUTO'
          - '--metrics_enable'
        env:
          - name: TS_SERVICE_ENVELOPE
            value: kserve
          - name: STORAGE_URI
            value: oci://{{ .Values.image_repository | default "quay.io" }}/{{ .Values.image_namespace }}/{{ .Values.name }}:{{ .Values.version }}
        image: 'quay.io/modh/openvino_model_server@sha256:6c7795279f9075bebfcd9aecbb4a4ce4177eec41fb3f3e1f1079ce6309b7ae45'
        name: kserve-container
        resources:
          limits:
            cpu: '3'
            memory: 8Gi
          requests:
            cpu: '1'
            memory: 4Gi
      - args:
          - '--model_name={{ .Values.name }}'
          - '--predictor_protocol=v2'
          - '--http_port=8080'
          - '--grpc_port=8081'
          - '--predictor_host=localhost:8085'
          - '--predictor_use_ssl=False'
          - '--scaler_file_path=/mnt/models/1/artifacts/scaler.pkl'
          - '--encoder_file_path=/mnt/models/1/artifacts/label_encoder.pkl'
        command:
          - python
          - '-m'
          - music_transformer
        image: 'quay.io/rhoai-mlops/music_transformer:0.1'
        name: transformer-container
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi