---
apiVersion: v2
description: A Helm chart for model deployments with Feast transformer
name: model-deployment-with-feast
version: 0.0.1
home: https://rhoai-mlops.github.io/mlops/
maintainers:
  - name: RHRolun
  - name: rcarrata
  - name: ckavili
