apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: music
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: jukebox
  namespace: test-mlops
  finalizers:
    - inferenceservice.finalizers
  labels:
    networking.knative.dev/visibility: cluster-local
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    containers:
      - args:
          - '--model_name=jukebox'
          - '--port=8001'
          - '--rest_port=8085'
          - '--model_path=/mnt/models'
          - '--file_system_poll_wait_seconds=0'
          - '--grpc_bind_address=0.0.0.0'
          - '--rest_bind_address=0.0.0.0'
          - '--target_device=AUTO'
          - '--metrics_enable'
        env:
          - name: TS_SERVICE_ENVELOPE
            value: kserve
          - name: STORAGE_URI
            value: 'oci://image-registry.openshift-image-registry.svc:5000/test-mlops/jukebox:latest'
        image: 'quay.io/modh/openvino_model_server@sha256:6c7795279f9075bebfcd9aecbb4a4ce4177eec41fb3f3e1f1079ce6309b7ae45'
        name: kserve-container
        resources:
          limits:
            cpu: '3'
            memory: 8Gi
          requests:
            cpu: '1'
            memory: 4Gi
      - args:
          - '--model_name=jukebox'
          - '--predictor_protocol=v2'
          - '--http_port=8080'
          - '--grpc_port=8081'
          - '--predictor_host=localhost:8085'
          - '--predictor_use_ssl=False'
          - '--scaler_file_path=models/jukebox/1/artifacts/scaler.pkl'
          - '--encoder_file_path=models/jukebox/1/artifacts/label_encoder.pkl'
        command:
          - python
          - '-m'
          - music_transformer
        envFrom:
          - secretRef:
              name: aws-connection-models
        image: 'quay.io/rlundber/music_transformer:0.19'
        name: transformer-container
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi