---
apiVersion: v2
description: A Helm chart for transactional database 🎸
name: database
version: 0.0.1
home: https://github.com/redhat-cop/helm-charts
maintainers:
  - name: RHRolun
  - name: rcarrata
  - name: ckavili