---
apiVersion: v1
kind: Service
metadata:
  name: feast
  labels:
    app: feast-database
spec:
  ports:
  - name: postgresql
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: feast-database
  sessionAffinity: None
  type: ClusterIP