---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.team }}-test-edit
  namespace: {{ .Values.team }}-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Values.team }}-mlops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.team }}-tekton-image-pusher-rolebinding
  namespace: {{ .Values.team }}-test
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Values.team }}-mlops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-pusher