{{ if eq .Values.linting true }}
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: linting
spec:
  workspaces:
    - name: output
  params:
    - name: WORK_DIRECTORY
      description: Directory to start build in (handle multiple branches)
      type: string
  steps:
  - name: linting
    workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
    image: registry.redhat.io/ubi9/python-311@sha256:fc669a67a0ef9016c3376b2851050580b3519affd5ec645d629fd52d2a8b8e4a
    command: ["/bin/sh", "-c"]
    args:
    - |
      python3 -m pip install flake8 pylint black
      # 🖤 Check code formatting with Black 🖤
      echo "🖤 Check code formatting with Black 🖤"
      black . --check --diff
      if [ $? -eq 1 ]; then
          echo "Code formatting check failed. Run 'black .' locally to fix."
          exit 1
        fi
      
      # ❄️ Lint with flake8 ❄️
      # stop the build if there are Python syntax errors or undefined names
      echo "Lint with flake8"
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Lint with pylint
      echo "Lint with pylint"
      pylint *.py --disable E0401 --disable E1120 --errors-only --exit-zero
{{- end }}