{{ if eq .Values.model_scanning true }}
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: scan-model
spec:
  workspaces:
    - name: output
  params:
    - name: APPLICATION_NAME
      description: Name of the application
      type: string
  steps:
  - name: scan-model
    workingDir: $(workspaces.output.path)
    image: quay.io/rlundber/mlops-ct-cicd:0.4
    command: ["/bin/sh", "-c"]
    args:
    - |
      python3 -m pip install modelscan
      modelscan -p /models/$(params.APPLICATION_NAME).keras
{{- end }}