---
apiVersion: triggers.tekton.dev/v1beta1 
kind: Trigger 
metadata:
  name: post-prod-deploy-trigger
spec:
  interceptors:
     - ref:
         name: "cel" 
       params:
        - name: filter
          value: body.commits.exists(c, "model-deployments/prod/jukebox/config.yaml" in c.modified)
        - name: overlays
          value:
          - expression: body.commits.map(c, c.modified)[1][0].split("/")[2]
            key: application_name
  bindings:
    - name: application_name
      value: $(extensions.application_name)
  template: 
     ref: post-prod-deploy-trigger-template
