---
apiVersion: v2
description: A Helm chart for enable and deploy Jukebox Grafana Dashboard 📊
name: jukebox-grafana
version: 0.0.1
home: https://rhoai-mlops.github.io/mlops/
maintainers:
  - name: RHRolun
  - name: rcarrata
  - name: ckavili