---
apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: {{ .Values.name }}-alerting
spec:
  route:
    receiver: default
  receivers:
  - name: default
    webhookConfigs:
      - url: >-
          http://el-ct-listener-{{ .Release.Namespace }}-mlops.svc.cluster.local:8080
