---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.name }}-alerts
spec:
  groups:
  - name: {{ .Values.name }}.rules
    rules:
    # example alert - more to add
    - alert: {{ .Values.name }}-datadrift-alert
      annotations:
        message: '{{ .Values.name }} has data drift...'
      expr: (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ .Release.Namespace }}"} * on(pod) group_left(label_app_kubernetes_io_component) kube_pod_labels{label_app_kubernetes_io_component="justtogeneratealert",namespace="{{ .Release.Namespace }}"})) == 0
      for: 10m
      labels:
        severity: "critical"

