---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.name }}-alerts
spec:
  groups:
  - name: {{ .Values.name }}.rules
    rules:
    # example alert - more to add
    - alert: {{ .Values.name }}-datadrift-alert
      annotations:
        message: '{{ .Values.name }} has data drift...'
      expr: trustyai_meanshift{namespace="{{ .Release.Namespace }}", subcategory="dense_4-8"}<0.05
      for: 10m
      labels:
        severity: "critical"

