---
apiVersion: triggers.tekton.dev/v1beta1	
kind: TriggerTemplate
metadata:
  name: post-prod-deploy-trigger-template
spec:
  params:
    - name: application_name
      description: The name of the application
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: post-prod-deploy-pipeline-
      spec:
        pipelineRef:
          name: post-prod-deploy-pipeline
        params:
          - name: APPLICATION_NAME
            value: $(tt.params.application_name)
        workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: shared-workspace

