---
apiVersion: triggers.tekton.dev/v1beta1 
kind: Trigger 
metadata:
  name: ct-trigger 
spec:
  interceptors:
     - ref:
         name: "cel" 
       params:
        # - name: filter
        #   value: (body.ref.event == 'push' && body.ref.split('/')[2] == 'main')
        - name: overlays
          value:
          - expression: body.checkout_sha.truncate(7)
            key: truncated_sha
          - expression: body.ref.split('/')[2]
            key: branch_name
  bindings:
    - name: git-branch
      value: $(extensions.branch_name)
    - name: git-short-revision
      value: $(extensions.truncated_sha)
    - name: git-revision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.project.git_http_url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-ref
      value: $(body.ref)
  template: 
     ref: ct-trigger-template
