---
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-data-job
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z -v -w30 $POSTGRESQL_DATABASE_HOST 5432; do echo "Waiting for database connection..."; sleep 2; done;']
        env:
        - name: POSTGRESQL_DATABASE_HOST
          value: transactionsdb.mlops-transactionsdb.svc.cluster.local
      containers:
      - name: postgresql
        image: registry.redhat.io/rhel9/postgresql-13:latest
        env:
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: transactionsdb
                key: database-name
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: transactionsdb
                key: database-user
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: transactionsdb
                key: database-password
          - name: POSTGRESQL_DATABASE_HOST
            value: transactionsdb.mlops-transactionsdb.svc.cluster.local
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Downloading data"
          rm -rf /data/card_transaction_data.csv
          curl --output /data/card_transaction_data.zip -L https://raw.githubusercontent.com/RHRolun/mlops/main/bootstrap/databases/data/card_transaction_data.zip
          unzip /data/card_transaction_data.zip
          head /data/card_transaction_data.csv
          echo "Copying into the database"
          psql -h $POSTGRESQL_DATABASE_HOST -p 5432 -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE -c "\copy transactions.transactions(transaction_id, distance_from_home, distance_from_last_transaction, ratio_to_median_purchase_price, repeat_retailer, used_chip, used_pin_number, online_order, fraud, event_timestamp) FROM '/data/card_transaction_data.csv' WITH (FORMAT csv, HEADER true);"
          # head -n 100001 /data/card_transaction_data.csv | psql -h $POSTGRESQL_DATABASE_HOST -p 5432 -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE -c "\copy transactions.transactions(transaction_id, distance_from_home, distance_from_last_transaction, ratio_to_median_purchase_price, repeat_retailer, used_chip, used_pin_number, online_order, fraud, event_timestamp) FROM stdin WITH (FORMAT csv, HEADER true);"
        volumeMounts:
        - name: sql-script-volume
          mountPath: /sql-script
        - name: data-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: sql-script-volume
        configMap:
          name: sql-script-configmap
      - name: data-volume
        persistentVolumeClaim:
            claimName: data-volume
  backoffLimit: 4