---
apiVersion: v1
kind: Service
metadata:
  name: transactionsdb
  labels:
    app: mlops-transactionsdb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - name: postgresql
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: mlops-transactionsdb
  sessionAffinity: None
  type: ClusterIP