---
apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  annotations:
    openshift.io/description: '{{ .Values.name }} Prod Model Registry'
    openshift.io/display-name: {{ .Values.name }}-prod-registry
  name: {{ .Values.name }}-prod-registry
  namespace: rhoai-model-registries
  finalizers:
    - modelregistry.opendatahub.io/finalizer
spec:
  grpc:
    port: 9090
  mysql:
    database: metadb
    host: {{ .Values.name }}-prod-registry-db.{{ .Values.name }}-toolings.svc.cluster.local
    passwordSecret:
      key: database-password
      name: {{ .Values.name }}-prod-registry-db
    port: 3306
    username: root
  oauthProxy:
    port: 8443
    routePort: 443
    serviceRoute: enabled
  rest:
    port: 8080
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    serviceRoute: disabled