---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.name }}-toolings-registry-db-parameters
  namespace: {{ .Values.name }}-toolings
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  MYSQL_DATABASE: metadb
  MYSQL_PORT: '3306'
