---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metadata-mysql
  namespace: {{ .Values.name }}-mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
