---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.name }}-prod-registry-db-secrets
  namespace: {{ .Values.name }}-toolings
data:
  MYSQL_ROOT_PASSWORD: dGVzdA==
  MYSQL_USER_NAME: cm9vdA==
type: Opaque
