---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dashboard-permissions-{{ .Values.name }}-toolings
  namespace: rhoai-model-registries
  labels:
    app: {{ .Values.name }}-prod-registry
    app.kubernetes.io/component: {{ .Values.name }}-prod-registry
    app.kubernetes.io/name: {{ .Values.name }}-prod-registry
    app.kubernetes.io/part-of: {{ .Values.name }}-prod-registry
    component: {{ .Values.name }}-prod-registry
    opendatahub.io/dashboard: 'true'
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Values.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-user-{{ .Values.name }}-prod-registry
