---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ct-alert-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: model-workspace
  params:
    - name: APPLICATION_NAME
      type: string
      default: ""
    - name: PROJECT_NAME
      type: string
      default: ""
    - name: VERSION
      type: string
      default: ""
    - name: GIT_REF
      type: string
      default: "refs/heads/main"
    - name: GIT_BRANCH
      type: string
      default: "main"
    - name: GIT_COMMIT_AUTHOR
      type: string
      default: "Prometheus Alerting"
  tasks:
    # Clone jukebox repository
    - name: fetch-ds-pipeline-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://{{ .Values.git_server }}/{{ .Values.USER_NAME }}/$(params.APPLICATION_NAME).git"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
        - name: deleteExisting
          value: "true"
        - name: sslVerify
          value: "false"

    # Execute Data Science Pipeline
    - name: execute-ds-pipeline
      taskRef:
        name: execute-ds-pipeline
        kind: Task
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)/3-prod_datascience"
        - name: APPLICATION_NAME
          value: "$(params.APPLICATION_NAME)"
        - name: VERSION
          value: "$(params.VERSION)"
      runAfter:
        - fetch-ds-pipeline-repository

    # Containerize the model (modelcar)
    - name: build-modelcar
      taskRef:
        name: build-modelcar
        kind: Task
      runAfter:
        - execute-ds-pipeline
      workspaces:
        - name: output
          workspace: model-workspace
      params:
        - name: APPLICATION_NAME
          value: "$(params.APPLICATION_NAME)"
        - name: VERSION
          value: "$(params.VERSION)"
        - name: PROJECT_NAME
          value: {{ .Values.USER_NAME }}

    # Fetch GitOps repository
    - name: fetch-gitops-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://{{ .Values.git_server }}/{{ .Values.USER_NAME }}/mlops-gitops.git"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "mlops-gitops/main"
        - name: deleteExisting
          value: "true"
        - name: sslVerify
          value: "false"
      runAfter:
        - build-modelcar

    # Update model version in Git
    - name: deploy-test
      taskRef:
        name: deploy-or-raise-pr
        kind: Task
      runAfter:
        - fetch-gitops-repository
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: APPLICATION_NAME
          value: "$(params.APPLICATION_NAME)"
        - name: VERSION
          value: "$(params.VERSION)"
        - name: WORK_DIRECTORY
          value: "mlops-gitops/main/model-deployments/"
        - name: DEPLOY_ENVIRONMENT
          value: "test"
        - name: PROJECT_NAME
          value: {{ .Values.USER_NAME }}
          
    # update model metadata
    - name: update-model-metadata
      taskRef:
        name: update-model-metadata
        kind: Task
      runAfter:
        - deploy-test
      params:
        - name: APPLICATION_NAME
          value: "$(params.APPLICATION_NAME)"
        - name: VERSION
          value: "$(params.VERSION)"
        - name: DEPLOY_ENVIRONMENT
          value: "test"
        - name: PROJECT_NAME
          value: {{ .Values.USER_NAME }}
        - name: KFP_RUN_ID
          value: "$(tasks.execute-ds-pipeline.results.KFP_RUN_ID)"
        - name: GIT_COMMIT_AUTHOR
          value: "$(params.GIT_COMMIT_AUTHOR)"

  results:
    - name: KFP_RUN_ID
      description: Run ID of the Data Science Pipeline
      value: "$(tasks.execute-ds-pipeline.results.KFP_RUN_ID)"
